// Static reference data for the wine form and cellar filters.
// These are suggestion lists, not closed enums — the form accepts free text
// for region, sub-region, varietal, and classification.

export const COUNTRIES: string[] = [
  'Argentina',
  'Australia',
  'Austria',
  'Bulgaria',
  'Canada',
  'Chile',
  'China',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'France',
  'Georgia',
  'Germany',
  'Greece',
  'Hungary',
  'India',
  'Israel',
  'Italy',
  'Japan',
  'Lebanon',
  'Mexico',
  'Moldova',
  'Morocco',
  'New Zealand',
  'Portugal',
  'Romania',
  'Slovenia',
  'South Africa',
  'Spain',
  'Switzerland',
  'Turkey',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Other',
]

export const WINE_STYLES: string[] = [
  'Red',
  'White',
  'Rosé',
  'Sparkling',
  'Dessert',
  'Fortified',
]

export const WINE_FORMATS: string[] = [
  '375mL (Half)',
  '750mL (Standard)',
  '1L',
  '1.5L (Magnum)',
  '3L (Double Magnum)',
  '6L (Imperial)',
  'Other',
]

export const COMMON_VARIETALS: string[] = [
  // Reds
  'Cabernet Sauvignon',
  'Merlot',
  'Pinot Noir',
  'Syrah / Shiraz',
  'Malbec',
  'Sangiovese',
  'Tempranillo',
  'Grenache',
  'Nebbiolo',
  'Zinfandel',
  'Cabernet Franc',
  'Petit Verdot',
  'Mourvèdre',
  'Gamay',
  'Barbera',
  'Bordeaux Blend',
  'Rhône Blend',
  'Red Blend',
  // Whites
  'Chardonnay',
  'Sauvignon Blanc',
  'Riesling',
  'Pinot Grigio / Pinot Gris',
  'Chenin Blanc',
  'Viognier',
  'Gewürztraminer',
  'Albariño',
  'Grüner Veltliner',
  'Moscato',
  'White Blend',
  // Sparkling / Fortified
  'Champagne / Sparkling Blend',
  'Port',
  'Sherry',
]

export const COMMON_REGIONS: string[] = [
  'Bordeaux',
  'Burgundy',
  'Champagne',
  'Rhône Valley',
  'Loire Valley',
  'Alsace',
  'Languedoc-Roussillon',
  'Tuscany',
  'Piedmont',
  'Veneto',
  'Sicily',
  'Rioja',
  'Ribera del Duero',
  'Priorat',
  'Douro',
  'Mosel',
  'Rheingau',
  'Napa Valley',
  'Sonoma County',
  'Willamette Valley',
  'Columbia Valley',
  'Central Coast',
  'Mendoza',
  'Maipo Valley',
  'Barossa Valley',
  'Margaret River',
  'Marlborough',
  'Stellenbosch',
]
